// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import ApplicationController from "./application_controller"
application.register("application", ApplicationController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import DisplayEmptyController from "./display_empty_controller"
application.register("display-empty", DisplayEmptyController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HovercardController from "./hovercard_controller"
application.register("hovercard", HovercardController)

import MessageComposerController from "./message_composer_controller"
application.register("message-composer", MessageComposerController)

import NavigationSelectController from "./navigation_select_controller"
application.register("navigation-select", NavigationSelectController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
