if Rails.env.production?
  require "exception_notification/rails"
  require "exception_notification/sidekiq"

  ExceptionNotification.configure do |config|
    # Ignore additional exception types.
    # ActiveRecord::RecordNotFound, Mongoid::Errors::DocumentNotFound, AbstractController::ActionNotFound and ActionController::RoutingError are already added.
    config.ignored_exceptions += %w[
      ActionDispatch::RemoteIp::IpSpoofAttackError
      ActionController::InvalidAuthenticityToken
      ActionController::RoutingError
      ActiveRecord::RecordNotFound
      ActionView::MissingTemplate
      Stripe::CardError
      URI::InvalidURIError
      OpenSSL::SSL::SSLError
      OutgoingWebhookResponseError
    ]

    # Adds a condition to decide when an exception must be ignored or not.
    # The ignore_if method can be invoked multiple times to add extra conditions.
    config.ignore_if do |exception, options|
      !Rails.env.production? && !Rails.env.staging?
    end

    # Ignore exceptions generated by crawlers
    # config.ignore_crawlers %w{Googlebot bingbot}

    # Notifiers =================================================================

    # Email notifier sends notifications by email.
    config.add_notifier :slack, {
      webhook_url: ENV["SLACK_EXCEPTIONS_WEBHOOK_URL"],
      username: "Happi error (#{Rails.env})",
      channel: "#happi-errors",
      additional_parameters: {
        mrkdwn: true
      }
    }
  end
end
